document.writeln("    <footer class=\'footer\'>");
document.writeln("      <div class=\'container\'>");
document.writeln("        <div class=\'row justify-content-end text-muted\'>");
document.writeln("          <div class=\'col-md-auto pull-right\' >");
document.writeln("            This is exercise for PHP + MySQL. If you want to see more. You can click");
document.writeln("            <a href=\'index.php\' class=\'text-muted\'>hear</a>.");
document.writeln("          </div>");
document.writeln("        </div>");
document.writeln("      </div>");
document.writeln("    </footer>");
document.writeln("");
document.writeln("    <!-- jQuery’s slim build -->");
document.writeln("    <script src=\'https://code.jquery.com/jquery-3.3.1.slim.min.js\' integrity=\'sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo\' crossorigin=\'anonymous\'></script>");
document.writeln("    <script src=\'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\' integrity=\'sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\' crossorigin=\'anonymous\'></script>");
document.writeln("    <script src=\'https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js\' integrity=\'sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T\' crossorigin=\'anonymous\'></script>    ");