document.writeln("<nav class=\'navbar navbar-expand-md navbar-dark bg-dark fixed-top\'>");
document.writeln("  <div class=\'container\'>");
document.writeln("    <a class=\'navbar-brand\' href=\'index.php\'>BookShops</a>");
document.writeln("    <button class=\'navbar-toggler\' type=\'button\' data-toggle=\'collapse\' data-target=\'#navbarSupportedContent\' aria-controls=\'navbarSupportedContent\' aria-expanded=\'false\' aria-label=\'Toggle navigation\'>");
document.writeln("      <span class=\'navbar-toggler-icon\'></span>");
document.writeln("    </button>");
document.writeln("");
document.writeln("    <div class=\'collapse navbar-collapse\' id=\'navbarSupportedContent\'>");
document.writeln("      <ul class=\'navbar-nav mr-auto\'>");
document.writeln("        <li class=\'nav-item active\'>");
document.writeln("          <a class=\'nav-link\' href=\'index.php\'>首頁 <span class=\'sr-only\'>(current)</span></a>");
document.writeln("        </li>");
document.writeln("        <li class=\'nav-item\'>");
document.writeln("          <a class=\'nav-link\' href=\'insert-book.php\'>新增書籍</a>");
document.writeln("        </li>");
document.writeln("        <li class=\'nav-item\'>");
document.writeln("          <a class=\'nav-link\' href=\'insert-writers.php\'>新增作者</a>");
document.writeln("        </li>");
document.writeln("        <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'insert-ph.php\'>新增出版社</a>");
document.writeln("        </li>");
document.writeln("        <li class=\'nav-item\'>");
document.writeln("            <a class=\'nav-link\' href=\'Personal-Information-Identification.php\'>個人資料類別辨識</a>");
document.writeln("        </li>");
document.writeln("      </ul>");
document.writeln("      <ul class=\'navbar-nav ml-auto\'>");
document.writeln("        <form class=\'form-inline my-2 my-lg-0\'>");
document.writeln("          <a class=\'pr-3 nav-link\' href=\'#\'>註冊</a>");
document.writeln("          <button class=\'btn btn-outline-light my-2 my-sm-0\' type=\'submit\'>登入</button>");
document.writeln("        </form>");
document.writeln("      </ul>");
document.writeln("    </div>");
document.writeln("  </div>");
document.writeln("</nav>");